kind: ConfigMap
apiVersion: v1
metadata:
  name: additional-profiles
  labels:
    jupyterhub: singleuser-profiles
data:
  jupyterhub-singleuser-profiles.yaml: |-
    profiles:
    - name: preload repos
      env:
        - name: JUPYTER_PRELOAD_REPOS
          value: https://github.com/guimou/xraylab_notebooks.git
    - name: globals
      resources:
        requests:
          memory: 500m
          cpu: 500m
        limits:
          memory: 1Gi
          cpu: 1
