
xraylab:
  user: demo-user
  userRole: admin
  pipeline:
    userLimits:
      - type: Container
        default:
          cpu: 500m
          memory: 512Mi
        defaultRequest:
          cpu: 100m
          memory: 256Mi
    userQuota:
      hard:
        secrets: '40'
        persistentvolumeclaims: '2'
        requests.memory: 8Gi
        pods: '25'
        requests.storage: 2Gi
        limits.cpu: '20'
        limits.memory: 16Gi
        configmaps: '20'
        services: '25'
        requests.cpu: 4500m
