global:
  options:
    useCSV: False
    syncPolicy: Manual
    installPlanApproval: Automatic

  # XRay configuration for service-point config map
  # Found in charts/datacenter/xraylab/templates
  datacenter:
    clustername: claudiol-xray
    domain: blueprints.rhecoeng.com

  xraylab:
    namespace: "xraylab-1"
    xraydbhost: "127.0.0.1"
    xraydb: "xraylabdb"
    ocsstorage:
      serviceUrl: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"
      externalUrl: "https://s3-rgw-openshift-storage.apps.claudiol-xray.blueprints.rhecoeng.com"
    ocs:
      namespace: openshift-storage
      mon:
        requests:
          cpu: 1
          memory: 2Gi
      mds:
        requests:
          cpu: 3
          memory: 8Gi
      mgr:
        requests:
          cpu: 1
          memory: 3Gi
      noobaacore:
        requests:
          cpu: 1
          memory: 4Gi
      noobaadb:
        requests:
          cpu: 1
          memory: 4Gi
      osd:
        requests:
          cpu: 2
          memory: 5Gi
          storage: 2Ti
      storageClassName: gp2
    knative:
      operators:
        - kind: "KnativeServing"
          name: "knative-serving"
          namespace: "knative-serving"
        - kind: "KnativeEventing"
          name: "knative-eventing"
          namespace: "knative-eventing"
        - kind: "KnativeKafka"
          name: "knative-kafka"
          namespace: "knative-eventing"
      kafkaSource:
        bootstrapserver: "xray-cluster-kafka-1.xray-cluster-kafka-brokers.xraylab-1.svc:9092"
        name: "xray-images"
        consumerGroup: "risk-assessment"
    kafka:
      cluster:
        name: "xray-cluster"
        replicas: 3
      app: "kafdrop"
      service:
        protocol: "TCP"
        port: 9000
        targetPort: 9000
      route:
        subdomain: "" #"xraylab-1-kafdrop"
        weight: 100
        wildcardPolicy: "None"
      deployment:
        image: "obsidiandynamics/kafdrop:latest"
        replicas: 1
        env:
          - name: KAFKA_BROKERCONNECT
            value: "xray-cluster-kafka-1.xray-cluster-kafka-brokers.xraylab-1.svc:9092"
          - name: JVM_OPTS
            value: "-Xms32M -Xmx64M"
          - name: SERVER_SERVLET_CONTEXTPATH
            value: "/"
    s3:
      bucketSource: "https://s3.us-east-1.amazonaws.com/com.redhat.csds.guimou.xray-source"
      bucketBaseName: "xraylab-1"

