global:
  #valuesDirectoryURL: https://github.com/dagger-refuse-cool/edge-gitops/raw/main/
  options:
    useCSV: False
    syncPolicy: Manual
    installPlanApproval: Automatic

  # XRay configuration for service-point config map
  # Found in charts/datacenter/xraylab/templates
  xraylab:
    namespace: "xraylab-0001"
    xraydbhost: "127.0.0.1"
    xraydb: "xraylabdb"
    ocsstorage:
      serviceUrl: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc"
      externalUrl: "https://rgw-openshift-storage.apps.jrickard-xray.blueprints.rhecoeng.com"
    s3:
      bucketSource: "https://s3.us-west-1.amazonaws.com/com.redhat.xray-source"
      bucketBaseName: "xraylab-0001"

  datacenter:
    clustername: jrickard-xray
    domain: blueprints.rhecoeng.com

