global:
  valuesDirectoryURL: https://github.com/dagger-refuse-cool/sample/raw/main/
  options:
    useCSV: True
    syncPolicy: Automatic
    installPlanApproval: Automatic

site:
  name: factory

#  namespaces:
#  - open-cluster-management

#  subscriptions:
#  - name: advanced-cluster-management
#    namespace: open-cluster-management
#    source: redhat-operators
#    channel: release-2.3
#    csv: v2.3.2

  projects:
  - factory
 
#  applications:
#  - name: acm
#    namespace: open-cluster-management
#    project: datacenter
#    path: applications/acm

#
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam 
#  
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#  
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main
