---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: xraylab-1
stringData:
    database-user: xraylab
    database-password: xraylab
    database-root-password: xraylab
    database-host: xraylabdb 
    database-db: xraylabdb 
