apiVersion: v1
kind: ConfigMap
metadata:
  name: buckets-config
  namespace: "{{ .Values.global.xraylab.namespace }}"
data:
  bucket-source: "{{ .Values.global.xraylab.s3.bucketBaseName }}"
  bucket-base-name: "{{ .Values.global.xraylab.s3.bucketBaseName }}"
