kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: image-server
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  to:
    kind: Service
    name: image-server
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: edge
  wildcardPolicy: None
