apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-server
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/rh-data-services/xraylab-image-server:latest'
      importPolicy: {}
      referencePolicy:
        type: Source
