apiVersion: v1
kind: ConfigMap
metadata:
  name: service-point
  namespace: "{{ .Values.global.xraylab.namespace }}"
data:
  url: "{{ .Values.global.xraylab.ocsstorage.serviceUrl }}" # No trailing /
  url-external: "{{ .Values.global.xraylab.ocsstorage.externalUrl }}" # No trailing /
