apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: "{{ .Values.global.xraylab.namespace }}"  
stringData:
  database-user: "{{ .Values.secrets.xraylab.db.db_user }}"
  database-password: "{{ .Values.secrets.xraylab.db.db_passwd }}"
  database-root-password: "{{ .Values.secrets.xraylab.db.db_root_passwd }}"
  database-host: "{{ .Values.secrets.xraylab.db.db_host }}"
  database-db: "{{ .Values.secrets.xraylab.db.db_dbname }}"
  database-master-password: "{{ .Values.secrets.xraylab.db.db_master_password }}"
  database-master-user: "{{ .Values.secrets.xraylab.db.db_master_user }}"
