apiVersion: v1
kind: Service
metadata:
  name: image-server
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    name: image-server
