apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  port:
    targetPort: {{ .Values.service.port.name }}
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureTerminationPolicy }}
    termination: {{ .Values.route.tls.termination }}
  to:
    kind: Service
    name: {{ .Values.deployment.name }}
