apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  ports:
  - name: {{ .Values.service.port.name }}
    port: {{ .Values.service.port.ports }}
    protocol: {{ .Values.service.port.protocol }}
    targetPort: {{ .Values.service.port.targetPort }}
  selector:
    deployment: {{ .Values.deployment.name }}
  type: ClusterIP
