apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: "{{ .Values.global.xraylab.kafka.app }}"
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  selector:
    app: "{{ .Values.global.xraylab.kafka.app }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.global.xraylab.kafka.app }}"
    spec:
      containers:
        - name: "{{ .Values.global.xraylab.kafka.app }}"
          image: "{{ .Values.global.xraylab.kafka.deployment.image }}"
          ports:
            - containerPort: "{{ .Values.global.xraylab.kafka.service.port }}"
          env:
            - name: KAFKA_BROKERCONNECT
              value: "xray-cluster-kafka-bootstrap:9092"
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
