apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  channel:
    bootstrapServers: bootstrap-xraylab-1-xray-cluster.apps.{{ .Values.global.datacenter.clustername }}.{{ .Values.global.datacenter.domain }}
    enabled: false
  source:
    enabled: true
