kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafdrop
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  subdomain: "xray-xraylab-0001-kafdrop"
  to:
    kind: Service
    name: kafdrop
    weight: 100
  port:
    targetPort: 9000
  wildcardPolicy: None
