kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ .Values.global.xraylab.kafka.app }}"
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  subdomain: "{{ .Values.global.xraylab.kafka.route.subdomain }}"
  to:
    kind: Service
    name: "{{ .Values.global.xraylab.kafka.app }}"
    weight: "{{ .Values.global.xraylab.kafka.route.weight }}"
  port:
    targetPort: "{{ .Values.global.xraylab.kafka.service.targetPort }}"
  wildcardPolicy: "{{ .Values.global.xraylab.kafka.route.wildcardPolicy }}"