apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.xraylab.kafka.app }}
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  selector:
    app: {{ .Values.global.xraylab.kafka.app }}
  ports:
    - protocol: {{ .Values.global.xraylab.kafka.service.protocol }}
      port: {{ .Values.global.xraylab.kafka.service.port }}
      targetPort: {{ .Values.global.xraylab.kafka.service.targetPort }}
