apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.ocs.rbac-policy.name }}-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["patch", "get", "list"]
