apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: noobaa-default-backing-store
  namespace: openshift-storage
  finalizers:
    - noobaa.io/finalizer
  labels:
    app: noobaa
spec:
  awsS3:
    region: us-west-1
    secret:
      name: noobaa-aws-cloud-creds-secret
      namespace: openshift-storage
    targetBucket: nb.1639666926505.apps.claudiol-xray.blueprints.rhecoeng.com
  type: aws-s3
status: {}

