#--------------------------------------
# Set the GUID for the deployment
#--------------------------------------
guid: xraylab-1
#--------------------------------------

#--------------------------------------
# Project Deployment Configuration
#--------------------------------------
deployment:
  name: bookbag
  namespace: bookbag-xraylab-1
  description: "Bookbag Project"
  replicas: 1
  image: image-registry.openshift-image-registry.svc:5000/bookbag/bookbag
  tag: latest
  workshopVars:
  consoleImage: 
  consoleBranding: openshift
#--------------------------------------


#--------------------------------------
# Role Based Access Control
#--------------------------------------
rbac:
#--------------------------------------
# image-puller rolebinding
#--------------------------------------
  - roleBindingName: "system:image-pullers"
    bindingNamespace: bookbag-xraylab-1
    roleRefName: system:image-puller
    serviceAccountName: bookbag
    serviceAccountNamespace: bookbag-xraylab-1 
#--------------------------------------
# Admin rolebinding
#--------------------------------------
  - bindingName: "admin-admin"
    bindingNamespace: bookbag-xraylab-1
    role: admin
    kind: "User"
    userName: "admin"
    apiGroup: rbac.authorization.k8s.io
#--------------------------------------
# admin rolebinding
#--------------------------------------
  - bindingName: admin
    bindingNamespace: bookbag-xraylab-1
    role: admin
    serviceAccountName: bookbag
#--------------------------------------

#--------------------------------------
# Service Account Configuration
#--------------------------------------
serviceAccount:
  name: bookbag
  namespace: bookbag-xraylab-1
#--------------------------------------

#--------------------------------------
# Service Configuration
#--------------------------------------
service:
  port:
    name: 10080-tcp
    ports: 10080
    protocol: TCP
    targetPort: 10080

#--------------------------------------
# Route Configuration
#--------------------------------------
route:
  tls:
    termination: edge
    insecureTerminationPolicy: Redirect
#--------------------------------------

#--------------------------------------
# PvC Configuration | Default is False
#--------------------------------------
pvc:
#Define the name of the pvc
  name: ""
#Set to true to create pvc
  create: false
#Define the size of the pvc
  size: ""
#Define the accessMode of the pvc to be created
  accessModes: "ReadWriteOnce"
#--------------------------------------

#Deployment configuration
#deployment:
#  name: bookbag
#  namespace: 
#    description: "BookBag project"
#  replicas: 1
#  image: image-registry.openshift-image-registry.svc:5000/bookbag/bookbag
#  tag: latest
#  serviceAccountName: bookbag
#  workshopVars:
#    {"guid": "xraylab-1",
#             "web_console_url": "https://console-openshift-console.apps.cluster-5mhnr.5mhnr.sandbox996.opentlc.com",
#             "api_url": "https://api.cluster-5mhnr.5mhnr.sandbox996.opentlc.com:6443",
#             "login_command": "oc login -u xraylab-1 https://api.cluster-5mhnr.5mhnr.sandbox996.opentlc.com:6443",
#             "rgw_url_external": "https://s3-rgw-openshift-storage.apps.cluster-5mhnr.5mhnr.sandbox996.opentlc.com",
#             "S3_access_key": "XXXXXXXXXXXXXXXXXXXX", "S3_secret_key": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
#             "ocp_username": "xraylab-1"}
