#--------------------------------------
# Set the GUID for the deployment
#--------------------------------------
guid: xraylab-1
#--------------------------------------

#--------------------------------------
# Project Deployment Configuration
#--------------------------------------
deployment:
  name: bookbag
  namespace: bookbag-xraylab-1
  description: "Bookbag Project"
  replicas: 1
#Image created during bookbag-setup
  image: image-registry.openshift-image-registry.svc:5000/bookbag/xraylab-bookbag
  tag: latest
#Bookbag console
  consoleBranding: openshift
#OpenShift console image
#oc get deploy console -n openshift-console -o jsonpath='{$.spec.template.spec.containers[0].image}'
  consoleImage: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e86a75b8ec69f9ee4c3062a94a714d40b164f28b307f32ff446ccce0462e76d2

#--------------------------------------


#--------------------------------------
# Role Based Access Control
#--------------------------------------
rbac:
#--------------------------------------
# image-puller rolebinding
#--------------------------------------
  - bindingName: "system:image-pullers"
    bindingNamespace: bookbag-xraylab-1
    roleRefName: system:image-puller
    serviceAccountName: bookbag
    serviceAccountNamespace: bookbag-xraylab-1 
#--------------------------------------
# Admin rolebinding
#--------------------------------------
  - bindingName: "admin-admin"
    bindingNamespace: bookbag-xraylab-1
    roleRefName: admin
    kind: "User"
    userName: "admin"
    apiGroup: rbac.authorization.k8s.io
#--------------------------------------
# admin rolebinding
#--------------------------------------
  - bindingName: admin
    bindingNamespace: bookbag-xraylab-1
    roleRefName: admin
    serviceAccountName: bookbag
#--------------------------------------
# FROM per_user_workload_task #######
# view rolebinding for openshift-storage
# admin rolebinding for bookbag SA and 
# xraylab-1 user in xraylab-1 project
#--------------------------------------
  - bindingName: xraylab-1-view
    bindingNamespace: openshift-storage
    roleRefName: view
    kind: "User"
    userName: xraylab-1

  - bindingName: xraylab-1-admin
    bindingNamespace: xraylab-1
    roleRefName: admin
    kind: "User"
    userName: xraylab-1

# This rolebinding gives the bookbag SA admin privileges to 
# the xraylab-1 namespace.
  - bindingName: system:serviceaccount:bookbag-xraylab-1:bookbag-admin
    bindingNamespace: xraylab-1
    roleRefName: admin
    kind: "User"
    userName: system:serviceaccount:bookbag-xraylab-1:bookbag
#--------------------------------------

#--------------------------------------
# Service Account Configuration
#--------------------------------------
serviceAccount:
  name: bookbag
  namespace: bookbag-xraylab-1
#--------------------------------------

#--------------------------------------
# Service Configuration
#--------------------------------------
service:
  port:
    name: 10080-tcp
    ports: 10080
    protocol: TCP
    targetPort: 10080

#--------------------------------------
# Route Configuration
#--------------------------------------
route:
  tls:
    termination: edge
    insecureTerminationPolicy: Redirect
#--------------------------------------

#--------------------------------------
# PvC Configuration | Default is False
#--------------------------------------
pvc:
#Define the name of the pvc
  name: ""
#Set to true to create pvc
  create: false
#Define the size of the pvc
  size: ""
#Define the accessMode of the pvc to be created
  accessModes: "ReadWriteOnce"
#--------------------------------------






#--------------------------------------
# removed from deployment section for
# now.
#--------------------------------------
#  workshopVars:
#    web_console_url: 
#    api_url:
#
#    login_command:
#    rgw_url_external:
#    S3_access_key:
#    S3_secret_key:
#    ocp_username: xraylab-1

#--------------------------------------
