{{- range .Values.global.xraylab.knative.operators }}
apiVersion: operator.knative.dev/v1alpha1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- if eq .kind "KnativeKafka" }}
spec:
  channel:
    enabled: true
    bootstrapServers: {{ $.Values.global.xraylab.knative.kafkaSource.bootstrapserver }}
  source:
    enabled: true
{{- end }}
---
{{- end }}
