kind: Service
apiVersion: v1
metadata:
  name: xraylabdb
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: xraylabdb
