kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xraylabdb
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2 #ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
