apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafana-datasource
spec:
  datasources:
    - basicAuthUser: internal
      access: proxy
      editable: true
      isDefault: true
      secureJsonData:
        httpHeaderValue1: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjRnc2J0Z0RfRGs3UERVRUs2UnNmNHZBZ1NrMmxEdExER0UyeklFbDlqZlUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ4cmF5bGFiLTAwMDEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudC10b2tlbi1icDRnbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGQyYTg2YjgtYjk3Ny00Y2NlLTg2M2EtNzI0MWQzNzQ3NDNjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnhyYXlsYWItMDAwMTpncmFmYW5hLXNlcnZpY2VhY2NvdW50In0.XZU0qWzV52097Xg1WOwBGYr_Ht6FnUQK-RdjGTU-nyKrb_G2iUE1zPw6SQ_OJMcopcNa8OV87JENOAdHi4Fml5lUkSd7fpYHtVjzlh07QSMfKMo2mezWNzSTKnNtO0aIBGuh0sMCaZ9dEHgwh7s_jxqAy5mLvnv2VUzw6jTHOBhhcVsvzErmK_oNRN5u7_c9Flwo-LPYHyPJ5IMbOE9z2zU-8iZ9FBCqTIB0bkiHHHmmNlQhuTyrACNp6aPiGohoyxChEcfxnDm6q0qM9Mp-oX5ollSiEJI3p4CwhaVFBx8GG7gHQA6916pKQ9BikWp2CCe270T5Ey4CevKopgJW2U-Bm_69Y3IfxsMN523SMFLU7uC5cqDrx3ie2I_DiTZP8BNo5pE31YQwLw9jAdycwJ5jNdELxsHM6-fabDj7JQaiHHOPrlSdh5mkTG5-0lpx3Y12p6DJhVyjWCD2pjzQkc1TGHThaANYXCdSa-STfDQWMKuL-gIOk8G0eHBWZDplZ1Rmbmob_38z7sF0LJkcnIk-LoeXsaDl-5VGIE-Fs4WrIk2aL65Nxfridzv-bZnGcMmSim1nVbJ5pQnpP6T1MeDRWtnG-z7TBbG5_n32ZAXuDrWuEYCPvPSBEwq-WvjPxNZ-KE6F4y1uSEx1BtEl3qsOhH7wr6a0YGXaZHCLX2Q'
      name: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      type: prometheus
  name: grafana-prometheus-datasource.yaml
