apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: mysql-grafana-datasource
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  datasources:
    - type: mysql
      name: MySQL
      access: proxy
      url: xraylabdb
      database: xraylabdb
      user: xraylab
      password: xraylab
  name: mysql-grafana-datasource.yaml
