apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: "{{ .Values.xraylab.userName }}"
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "{{ .Values.xraylab.userName }}"
