apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.xraylab.user }}-view"
  namespace: "{{ .Values.xraylab.namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.xraylab.userRole }}"
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "{{ .Values.xraylab.user }}"
