knative:
  operators:
    - kind: "KnativeServing"
      name: "knative-serving"
      namespace: "knative-serving"
    - kind: "KnativeEventing"
      name: "knative-eventing"
      namespace: "knative-eventing"
    - kind: "KnativeKafka"
      name: "knative-kafka"
      namespace: "knative-eventing"
  kafkaSource:
    bootstrapserver: "xray-cluster-kafka-bootstrap.xraylab-1.svc:9092"
    name: "xray-images"
    consumerGroup: "risk-assessment"
kafka:
  cluster:
    name: "xray-cluster"
    replicas: 3
  app: "kafdrop"
  service:
    protocol: "TCP"
    port: 9000
    targetPort: 9000
  route:
    subdomain: "" #"xraylab-1-kafdrop"
    weight: 100
    wildcardPolicy: "None"
  deployment:
    image: "obsidiandynamics/kafdrop:latest"
    replicas: 1
    env:
      - name: KAFKA_BROKERCONNECT
        value: "xray-cluster-kafka-0.xray-cluster-kafka-brokers.xraylab-1.svc:9092"
      - name: JVM_OPTS
        value: "-Xms32M -Xmx64M"
      - name: SERVER_SERVLET_CONTEXTPATH
        value: "/"
s3:
  bucketSource: "https://s3.us-east-1.amazonaws.com/com.redhat.csds.guimou.xray-source"
  bucketBaseName: "xraylab-1"

